version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_USER=root
      - DB_PASSWORD=9930
      - DB_HOST=db
      - DB_NAME=test_db
    depends_on:
      - db
    command: sh -c "sleep 10 && python app.py"  # Wait for DB to be ready

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 9930
      MYSQL_DATABASE: test_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: